# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    assignees:
      - "ubc-uas"
    insecure-external-code-execution: deny
    labels:
      - "Priority: Medium"
      - "Status: Review Needed"
      - "Type: Dependency"
    open-pull-requests-limit: 10
    reviewers:
      - "ubcuas/software-leads"
      - "ubcuas/ACOM"
