version: "3"
services:
  flask:
    build:
      context: ./flaskr
      dockerfile: Dockerfile
    environment:
      FLASK_APP: flaskr
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    command: [ "flask", "run" ]
    tty: true
    ports:
      - 5000:5000
    hostname: acom-server
    networks:
      acomnet:
        ipv4_address: 164.2.0.2
    depends_on:
      - sitl
    volumes:
      - ./:/app

  sitl:
    image: ubcuas/uasitl:latest
    environment:
      NUMCOPTERS: 1
      # Set location to UBC thunderbird field
      LAT: 49.2592231
      LON: -123.2415589
      ALT: 96
    tty: true
    ports:
      - 5760-5780:5760-5780
    hostname: acom-sitl
    networks:
      acomnet:
        ipv4_address: 164.2.0.3


networks:
  acomnet:
    driver: bridge
    ipam:
      config:
        - subnet: 164.2.0.0/16
