name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: make docker
    - name: Run tests
      run: make ci-test
    - name: Publish Docker image
      if: ${{ github.event_name == 'push' }}
      run: |
        docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
        docker-publish-arm
  
  build-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: dietpi:rpi_armv7_bullseye
        cpu: cortex-a7
        commands: |
          sudo apt-get -y install make
          make docker-arm
          make ci-test
    - name: Publish Docker image
      if: ${{ github.event_name == 'push' }}
      run: |
        docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
        docker-publish-arm
